// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a source generator named Intellenum (https://github.com/SteveDunn/Intellenum)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0618

// Suppress warnings for 'Override methods on comparable types'.
#pragma warning disable CA1036

// Suppress Error MA0097 : A class that implements IComparable<T> or IComparable should override comparison operators
#pragma warning disable MA0097

// Suppress warning for 'The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.'
// The generator copies signatures from the BCL, e.g. for `TryParse`, and some of those have nullable annotations.
#pragma warning disable CS8669

// Suppress warnings about CS1591: Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable CS1591

using Intellenum;
using System;

namespace Intellenum.IntegrationTests.TestTypes.ClassVos
{

    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage] 
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Intellenum", "0.0.0.0")]
    [global::System.ComponentModel.TypeConverter(typeof(NoJsonDateTimeVoTypeConverter))]

    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(NoJsonDateTimeVoDebugView))]
    [global::System.Diagnostics.DebuggerDisplayAttribute("Underlying type: System.DateTime, Value = { _value }")]
    public partial class NoJsonDateTimeVo : 
        global::System.IEquatable<NoJsonDateTimeVo>, 
        global::System.IEquatable<System.DateTime>, 
        global::System.IComparable, 
        global::System.IComparable<NoJsonDateTimeVo> 
    {
                private static readonly System.Lazy<System.Collections.Generic.Dictionary<string, System.DateTime>> _namesToValues = new( () =>
        new()
        {
            { "Item1", Item1.Value },
{ "Item2", Item2.Value },

        });
        private static readonly System.Lazy<System.Collections.Generic.Dictionary<string, NoJsonDateTimeVo>> _namesToEnums = new( () =>
        new()
        {
            { "Item1", Item1 },
{ "Item2", Item2 },

        });
        private static readonly System.Lazy<System.Collections.Generic.Dictionary<NoJsonDateTimeVo, System.DateTime>> _enumsToValues = new( () =>
        new()
        {
            { Item1, Item1.Value },
{ Item2, Item2.Value },

        });
        private static readonly System.Lazy<System.Collections.Generic.Dictionary<System.DateTime, string>> _valuesToNames = new( () =>
        new()
        {
            { Item1.Value, "Item1" },
{ Item2.Value, "Item2" },

        });
        private static readonly System.Lazy<System.Collections.Generic.Dictionary<System.DateTime, NoJsonDateTimeVo>> _valuesToEnums = new( () =>
        new()
        {
            { Item1.Value, Item1 },
{ Item2.Value, Item2 },

        });

#if DEBUG    
        private readonly global::System.Diagnostics.StackTrace _stackTrace = null;
#endif
        private readonly global::System.Boolean _isInitialized;
        private readonly System.DateTime _value;

        

        /// <summary>
        /// Gets the underlying <see cref="System.DateTime" /> value if set, otherwise default
        /// </summary>
        public System.DateTime Value
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            [global::System.Diagnostics.DebuggerStepThroughAttribute]
            get
            {
                return _value;
            }
        }

private void Throw()
{
#if DEBUG
                global::System.String message = "Use of uninitialized Value Object at: " + _stackTrace ?? "";
#else
                global::System.String message = "Use of uninitialized Value Object.";
#endif

                throw new IntellenumUninitialisedException(message);

}

        [global::System.Diagnostics.DebuggerStepThroughAttribute]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public NoJsonDateTimeVo()
        {
#if DEBUG
            _stackTrace = new global::System.Diagnostics.StackTrace();
#endif
            _isInitialized = false;
            _value = default;
            Name = "[UNDEFINED]";
        }

        [global::System.Diagnostics.DebuggerStepThroughAttribute]
        private NoJsonDateTimeVo(System.DateTime value)
        {
            _value = value;
            Name = "[INFERRED-TO-BE-REPLACED!]";
            _isInitialized = true;
        }        

        [global::System.Diagnostics.DebuggerStepThroughAttribute]
        private NoJsonDateTimeVo(string enumName, System.DateTime value)
        {
            _value = value;
            Name = enumName;
            _isInitialized = true;
        }

        public string Name { get; private set; }

        /// <summary>
        /// Builds an instance from an enum value.
        /// </summary>
        /// <param name="value">The value.</param>
        /// <returns>The matching enum, or an exception.</returns>
        public static NoJsonDateTimeVo FromValue(System.DateTime value)
        {
                bool b =  _valuesToEnums.Value.TryGetValue(value, out var ret);
    if(b) return ret;
    throw new IntellenumMatchFailedException($"NoJsonDateTimeVo has no matching instances with a value of '{value}'");
        }            

        /// <summary>
        /// Tries to get an instance based on value.
        /// </summary>
        /// <param name="value">The value.</param>
        /// <returns>The matching enum, or an exception.</returns>
        public static bool TryFromValue(System.DateTime value, out NoJsonDateTimeVo instance)
        {
            return  _valuesToEnums.Value.TryGetValue(value, out instance);
        }        

        public static bool IsDefined(System.DateTime value)
        {
            return _valuesToEnums.Value.TryGetValue(value, out _);
        }

        public void Deconstruct(out string Name, out System.DateTime Value)
        {
            Name = this.Name;
            Value = this.Value;
        }

        /// <summary>
        /// Gets the matching instance based on name.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <returns>The matching enum, or an exception.</returns>
        public static NoJsonDateTimeVo FromName(string name)
        {
                bool b = TryFromName(name, out var ret);
    if(b) return ret;
    throw new IntellenumMatchFailedException($"NoJsonDateTimeVo has no matching instances named '{name}'");
        }

        /// <summary>
        /// Tries to get the matching instance from a name.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <returns>The matching enum, or an exception.</returns>
        public static bool TryFromName(string name, out NoJsonDateTimeVo instance)
        {
            return _namesToEnums.Value.TryGetValue(name, out instance);
        }

        public static bool IsNamedDefined(string name)
        {
            return TryFromName(name, out _);
        }


        /// <summary>
        /// Builds an instance from the provided underlying type.
        /// </summary>
        /// <param name="value">The underlying type.</param>
        /// <returns>An instance of this type.</returns>
        private static NoJsonDateTimeVo From(string name, System.DateTime value)
        {
            

            NoJsonDateTimeVo instance = new NoJsonDateTimeVo(name, value);

            return instance;
        }

        // placeholder method used by the source generator
        // to generate physical instances (e.g. public static readonly MyEnum Item1 = new...)
        private static void Instance(string name, System.DateTime value)
        {
        }

        // only called internally when something has been deserialized into
        // its primitive type.
        private static NoJsonDateTimeVo Deserialize(System.DateTime value)
        {
            

                    if(value == Item1.Value) return Item1;
        if(value == Item2.Value) return Item2;


            return FromValue(value);
        }

        public global::System.Boolean Equals(NoJsonDateTimeVo other)
        {
            if (ReferenceEquals(null, other))
            {
                return false;
            }

            // It's possible to create uninitialized instances via converters such as EfCore (HasDefaultValue), which call Equals.
            // We treat anything uninitialized as not equal to anything, even other uninitialized instances of this type.
            if(!_isInitialized || !other._isInitialized) return false;
	    	
            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return GetType() == other.GetType() && global::System.Collections.Generic.EqualityComparer<System.DateTime>.Default.Equals(Value, other.Value);
        }

        public global::System.Boolean Equals(System.DateTime primitive) => Value.Equals(primitive);

        public override global::System.Boolean Equals(global::System.Object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (obj.GetType() != GetType())
            {
                return false;
            }

            return Equals((NoJsonDateTimeVo) obj);
        }

        public static global::System.Boolean operator ==(NoJsonDateTimeVo left, NoJsonDateTimeVo right) => Equals(left, right);
        public static global::System.Boolean operator !=(NoJsonDateTimeVo left, NoJsonDateTimeVo right) => !Equals(left, right);

        public static global::System.Boolean operator ==(NoJsonDateTimeVo left, System.DateTime right) => Equals(left.Value, right);
        public static global::System.Boolean operator !=(NoJsonDateTimeVo left, System.DateTime right) => !Equals(left.Value, right);

        public static global::System.Boolean operator ==(System.DateTime left, NoJsonDateTimeVo right) => Equals(left, right.Value);
        public static global::System.Boolean operator !=(System.DateTime left, NoJsonDateTimeVo right) => !Equals(left, right.Value);
        
        public static global::System.Boolean operator <(NoJsonDateTimeVo left, NoJsonDateTimeVo right) => left.CompareTo(right) < 0;
        public static global::System.Boolean operator <=(NoJsonDateTimeVo left, NoJsonDateTimeVo right) => left.CompareTo(right) <= 0;
        public static global::System.Boolean operator >(NoJsonDateTimeVo left, NoJsonDateTimeVo right) => left.CompareTo(right) > 0;
        public static global::System.Boolean operator >=(NoJsonDateTimeVo left, NoJsonDateTimeVo right) => left.CompareTo(right) >= 0;

        public static explicit operator NoJsonDateTimeVo(System.DateTime value) => FromValue(value);
        public static implicit operator System.DateTime(NoJsonDateTimeVo value) => value.Value;

        public int CompareTo(NoJsonDateTimeVo other) => Value.CompareTo(other.Value);
        public int CompareTo(object other) {
            if(other == null) return 1;
            if(other is NoJsonDateTimeVo x) return CompareTo(x);
            throw new global::System.ArgumentException("Cannot compare to object as it is not of type NoJsonDateTimeVo", nameof(other));
        }

        public override global::System.Int32 GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                global::System.Int32 hash = (global::System.Int32) 2166136261;
                hash = (hash * 16777619) ^ Value.GetHashCode();
                hash = (hash * 16777619) ^ GetType().GetHashCode();
                hash = (hash * 16777619) ^ global::System.Collections.Generic.EqualityComparer<System.DateTime>.Default.GetHashCode();
                return hash;
            }
        }

        
// instance...

public static readonly NoJsonDateTimeVo Item3 = new NoJsonDateTimeVo("Item3",new DateTime(2022, 01, 15, 19, 08, 49, DateTimeKind.Utc).AddTicks(5413764));
public static readonly NoJsonDateTimeVo Item1 = new NoJsonDateTimeVo("Item1",new DateTime(2019, 12, 13, 14, 15, 16));

// instance...

public static readonly NoJsonDateTimeVo Item2 = new NoJsonDateTimeVo("Item2",new DateTime(2020, 12, 13, 14, 15, 16));

        
        public static global::System.Collections.Generic.IEnumerable<NoJsonDateTimeVo> List()
        {
            yield return Item1;
yield return Item2;

        }        

        /// <summary>Returns the name of the enum.</summary>
    public override global::System.String ToString() => Name;

        


        class NoJsonDateTimeVoTypeConverter : global::System.ComponentModel.TypeConverter
        {
            public override global::System.Boolean CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext context, global::System.Type sourceType)
            {
                return sourceType == typeof(global::System.DateTime) || sourceType == typeof(global::System.String) || base.CanConvertFrom(context, sourceType);
            }

            public override global::System.Object ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext context, global::System.Globalization.CultureInfo culture, global::System.Object value)
            {
                return value switch
                {
                    global::System.String stringValue when !global::System.String.IsNullOrEmpty(stringValue) &&
                                                           global::System.DateTime.TryParseExact(stringValue, "O",
                                                               global::System.Globalization.CultureInfo.InvariantCulture,
                                                               global::System.Globalization.DateTimeStyles.RoundtripKind, out var result) =>
                        NoJsonDateTimeVo.Deserialize(result),
                    global::System.DateTime dateTimeValue => NoJsonDateTimeVo.Deserialize(dateTimeValue),
                    _ => base.ConvertFrom(context, culture, value),
                };
            }

            public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext context, global::System.Type sourceType)
            {
                return sourceType == typeof(global::System.DateTime) || sourceType == typeof(global::System.String) || base.CanConvertTo(context, sourceType);
            }

            public override object ConvertTo(global::System.ComponentModel.ITypeDescriptorContext context, global::System.Globalization.CultureInfo culture, global::System.Object value, global::System.Type destinationType)
            {
                if (value is NoJsonDateTimeVo idValue)
                {
                    if (destinationType == typeof(global::System.DateTime))
                    {
                        return idValue.Value;
                    }

                    if (destinationType == typeof(global::System.String))
                    {
                        return idValue.Value.ToString("O", global::System.Globalization.CultureInfo.InvariantCulture);
                    }
                }

                return base.ConvertTo(context, culture, value, destinationType);
            }
        }




        
        
    /// <inheritdoc cref="System.DateTime.TryParse(string, out System.DateTime)"/>
    /// <summary>
    /// </summary>
    /// <returns>
    /// The value created via the <see cref="From"/> method.
    /// </returns>
    /// <exception cref="IntellenumValidationException">Thrown when the value can be parsed, but is not valid.</exception>
    public static global::System.Boolean TryParse(string s, 
#if NETCOREAPP3_0_OR_GREATER
[global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
#endif
 out NoJsonDateTimeVo result) {
        if(System.DateTime.TryParse(s, out var r)) {
            result = FromValue(r);
            return true;
        }

        result = default;
        return false;
    }

    /// <inheritdoc cref="System.DateTime.TryParse(string, System.IFormatProvider, System.Globalization.DateTimeStyles, out System.DateTime)"/>
    /// <summary>
    /// </summary>
    /// <returns>
    /// The value created via the <see cref="From"/> method.
    /// </returns>
    /// <exception cref="IntellenumValidationException">Thrown when the value can be parsed, but is not valid.</exception>
    public static global::System.Boolean TryParse(string s, global::System.IFormatProvider provider, global::System.Globalization.DateTimeStyles styles, 
#if NETCOREAPP3_0_OR_GREATER
[global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
#endif
 out NoJsonDateTimeVo result) {
        if(System.DateTime.TryParse(s, provider, styles, out var r)) {
            result = FromValue(r);
            return true;
        }

        result = default;
        return false;
    }


        internal sealed class NoJsonDateTimeVoDebugView
        {
            private readonly NoJsonDateTimeVo _t;

            NoJsonDateTimeVoDebugView(NoJsonDateTimeVo t)
            {
                _t = t;
            }

            public global::System.String UnderlyingType => "System.DateTime";
            public System.DateTime Value => _t.Value ;

            public global::System.String Conversions => @"[global::System.ComponentModel.TypeConverter(typeof(NoJsonDateTimeVoTypeConverter))]
";
                }
    }
}