name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
              8.0.x
              7.0.x
              6.0.x
              5.0.x
              3.1.x
      - name: Build and Test
        run: ./Build.ps1
        shell: pwsh
      - name: Publish
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}  --skip-duplicate -s https://api.nuget.org/v3/index.json